<div class="subbody-frame" style="z-index:-1;">
	<div class="auContent">

        <!-- about -->
        <div class="auHeader">Terms</div>


        <div>
			<div id="tabbed_box_1" class="tabbed_box">
				<div class="tabbed_area">
					<ul class="ktabs">
						<li id="billing" class="kerio-tab active">BILLING</li>
						<li id="dmca" class="kerio-tab">DMCA</li>
						<li id="privacy" class="kerio-tab">PRIVACY</li>
						<li id="sla" class="kerio-tab">SLA</li>
						<li id="tos" class="kerio-tab">TERMS OF SERVICE</li>
						<li id="aup" class="kerio-tab">ACCEPTABLE USE</li>
					</ul>
					<div id="billing-content" class="kcontent">
						<p class="auSubHeader">Premium Accounts</p>
						<p class="auTextBlock">For a subscription fee, Kerio offers You the option of increasing Your account storage space beyond the initial free offering by converting to a Premium Account. The subscription fees are provided at the <a href="?pricing" class="auLoc-link">Pricing Tab</a>, unless otherwise agreed upon with us in a separate writing. The pricing stated excludes all taxes or other charges that may be applied to Your transaction by local government agencies. You are also responsible for any incidental 3rd party charges for using the Samepage, e.g., charges for Internet access, data roaming, and other data transmission charges. Please note that Your subscription fees are subject to change at any time, without notice, although we will attempt to notify You by email.</p>
						<p class="auSubHeader">Billing and Payment</p>
						<p class="auTextBlock">Converting to a Premium Account requires You to provide a valid credit card for payment purposes. On the day You upgrade to Your Premium Account, You will receive Your first invoice and Your credit card will be charged. Thereafter, on the day before each subsequent subscription anniversary date, Kerio will automatically charge your credit card, on a monthly, quarterly or annually basis  depending upon which billing option You select, unless and until You cancel Your Premium Account. You will also receive a new invoice each time You make changes to Your account. It is Your responsibility to keep Your account information current and updated.</p>
						<p class="auTextBlock">You acknowledge that the amount billed each month, quarter or year may vary for reasons that include but are not limited to differing amounts due to promotional offers, changes in Your subscription fee pricing, and changes in Your account (e.g., adding users and extra storage); You authorize us to charge Your credit card for such varying amounts. Kerio’s general policy is that all fees and charges are nonrefundable and that there are no refunds or credits for partially used periods; exceptions to this policy will be addressed with on a case-by-case basis.</p>
						<p class="auTextBlock">If any subscription fees are not paid in a timely manner, or we are unable to process Your transaction using the credit card information provided, we reserve the right to suspend access to and/or terminate Your Premium Account. However, we will promptly notify You of any payment or past due balance issues via email, and of our intent to take negative action regarding Your Premium Account before doing so. We also reserve the right to assess a late charge on any unpaid balance, at the rate of the lesser of 1% of such balance or the maximum rate permitted by law. To the extent that we are unable to collect unpaid balances from You, we may use a third party to seek collection. You agree to pay for all reasonable costs we incur regarding such collection efforts, including but not limited to reasonable attorneys' fees and other legal fees and costs.</p>
						<p class="auSubHeader">Cancelling Your Account</p>
						<p class="auTextBlock">Your Premium Account will continue in effect unless and until You cancel it or we terminate it. You must cancel Your Premium Account before it renews each month, quarter or year in order to avoid billing of the next period's fees to Your credit card. If You wish to cancel Your Premium Account You may do so by contacting <a href="/help/" class="auLoc-link">Customer Support</a>.</p> 
						<p class="auTextBlock">By signing up for a Kerio Premium Account and providing Kerio with Your payment information, You hereby agree to these Billing Terms.</p>
						<p class="auFinePrint">For further information regarding Your Premium or Free Account, please see the <a href="/cloud/terms/?tos" class="auLoc-link">Samepage Terms of Service</a>.</p>
					</div>
					<div id="dmca-content" class="kcontent">
						<p class="auSubHeader">Samepage DMCA Policy</p>
						<p class="auTextBlock">Kerio respects the intellectual property rights of others and expects its users to do the same. In accordance with the Digital Millennium Copyright Act of 1998, the text of which may be found on the U.S. Copyright Office website at http://www.copyright.gov/legislation/dmca.pdf, Kerio will respond expeditiously to claims of copyright infringement committed using Samepage Services (the “Services”) and/or the Samepage Website (the “Website”) if such claims are reported to Kerio’s Designated Copyright Agent identified in the sample notice below.</p>
						<p class="auTextBlock">If You are a copyright owner, authorized to act on behalf of one, or authorized to act under any exclusive right under copyright, please report alleged copyright infringements taking place on the Services on or through the Website by completing the following DMCA Notice of Alleged Infringement and delivering it to Kerio’s Designated Copyright Agent. Upon receipt of Notice as described below, Kerio will take whatever action, in its sole discretion, it deems appropriate, including removal of the challenged content from the Site.</p>
						<div class="auDocWrapper">
							<p class="auSubBlock-header">DMCA Notice of Alleged Infringement (“Notice”)</p>
							<ol class="auSubBlock-ol">
								<li class="auSubBlock-ol">Identify the copyrighted work that You claim has been infringed, or if multiple copyrighted works are covered by this Notice You may provide a representative list of the copyrighted works that You claim have been infringed.</li>
								<li class="auSubBlock-ol">Identify the material or link You claim is infringing (or the subject of infringing activity) and to which access is to be disabled, including at a minimum, if applicable, the URL of the link shown on the Services or on the Website or the exact location where such material may be found.</li>
								<li class="auSubBlock-ol">Provide Your company affiliation (if applicable), mailing address, telephone number, and, if available, email address.</li>
								<li class="auSubBlock-ol">Include both of the following statements in the body of the Notice:<br />
									<ul class="auTextBlock-li-disc">
										<li class="auTextBlock-li-disc">"I hereby state that I have a good faith belief that the disputed use of the copyrighted material is not authorized by the copyright owner, its agent, or the law (e.g., as a fair use)."</li>
										<li class="auTextBlock-li-disc">I hereby state that the information in this Notice is accurate and, under penalty of perjury, that I am the owner, or authorized to act on behalf of, the owner, of the copyright or of an exclusive right under the copyright that is allegedly infringed.</li>
									</ul>
								</li>
								<li class="auSubBlock-ol">Provide Your full legal name and Your electronic or physical signature.</li>
							</ol>
						</div>
						<p>&nbsp;</p>
						<p class="auTextBlock">Deliver this Notice, with all items completed, to Kerio’s Designated Copyright Agent:</p>
						<p class="auTextBlock">
							<font class="auLoc-title">Copyright Agent</font><br />
							c/o General Counsel<br />
							Kerio Technologies Inc.<br />
							111 North Market Street<br />
							6th Floor<br />
							San Jose, CA 95113<br />
							Phone 408-496-3355<br />
							<a href="mailto:legal@kerio.com" class="auLoc-link">mailto:legal@kerio.com</a>
						</p>
					</div>
					<div id="privacy-content" class="kcontent">
						<p class="auSubHeader">Samepage Privacy Policy</p>
						<p class="auTextBlock">At Kerio Technologies Inc. (“Kerio”), we know that You care about how information about You is used and shared, and we appreciate Your trust that we will do so carefully and sensibly. Please read the following to understand what Information we collect, how we use that Information, to whom we may disclose that Information, and how we safeguard that Information. Because the Internet is global, the Information about You that we collect or that You submit may be transferred to, processed in, and stored in countries (including the United States) other than the one in which You reside. By using our various Websites and our Products and Services, You explicitly consent to such use of Your Information and agree to the terms of this Privacy Policy.</p>
						<p class="auTextBlock">Kerio reserves the right to change or update this Privacy Policy as our business evolves. Please review this Privacy Policy periodically. Any updated version of this Privacy Policy will be effective as of the date specified in such update. Please note that the individual terms and conditions of usage of particular Products and Services may be more restrictive than those contained herein. Finally, be advised that this Privacy Policy includes Kerio’s European Union and Swiss Safe Harbor Privacy statements.</p>
						<p class="auSubHeader">What Information We Collect</p>
						<p class="auTextBlock">As a visitor of our Website, You can engage in many activities without providing any Personal Information. However, we do automatically receive certain types of information when You interact with our webpages (e.g., IP address, browser type, software and operating system used, device type, carrier). Kerio also uses cookies, which are small text files that a web site can send to Your browser to be stored automatically on Your computer. You may set Your browser to reject or disable cookies, however be advised that You may be prevented access to certain parts of our Website if You do so. Kerio may also use clear GIFs, which are one pixel graphic image files on our Website that may collect the time the GIF was viewed or the type of browser that requested the image file.</p>
						<p class="auTextBlock">If You register as a customer, download free evaluation software, upgrades, order e-mail newsletters or engage in other activities, Kerio may ask You to register by filling out an online form, where You will be asked to provide information that personally identifies You and/or Your company name (e.g., address, email address, phone number, title/position, demographics, etc.).  When You purchase one of our Products or Services direct from Kerio, You may also be asked for Your credit card or other financial/payment information.  We also “collect” on Your behalf what You upload or input while using the Services, such as information, data or files, although we do not use anything uploaded. We also collect information from surveys, contests and sweepstakes.  </p>
						<p class="auTextBlock">In addition to personal information, we collect aggregated data, which we define as anonymized (non-personalized) information about a group or category of services or users from which individual user identities have been removed. For example, we may collect information regarding type of company, size and number of users, usage characteristics, and other information regarding usage profiles. Such information may be used for internal business purposes or provided to partners or other associated third parties without restriction.  However, no personal information is included in aggregated data. We simply collect aggregated data to help us understand our users’ needs and to improve our Products and Services by considering new features and functionality or otherwise tailoring our Products and Services. We may share aggregated data about our users with third parties for similar purposes. We may also use such information even if and after You stop using our Products or Services.</p>
						<p class="auSubHeader">How We Use the Information We Collect</p>
						<p class="auTextBlock">In general, we use Your personal information to process Your requests and transactions, to provide You with the Products and Services You request, to alert You to upgrades and updates, and to share with You special offers and updated information we think will be of interest to You. We also use aggregated data to make the Website easier to use, to improve site performance and content, and to monitor web traffic and usage. Credit card numbers are only used for payment processing and are not retained for marketing purposes.</p>
						<p class="auSubHeader">Safe Harbor Compliance</p>
						<p class="auTextBlock">Kerio may store and process personal information in the United States and other countries. We adhere to the U.S. Department of Commerce’s Safe Harbor privacy principles regarding the collection, use, and retention of personal information from the European Union, and the U.S. Department of Commerce’s U.S. Swiss Safe Harbor privacy principles regarding the collection, use, and retention of personal information from Switzerland. Our Safe Harbor certifications can be found at <a href="http://web.ita.doc.gov/safeharbor/shlist.nsf/webPages/safe+harbor+list" class="auLoc-link" target="_blank">http://web.ita.doc.gov/safeharbor/shlist.nsf/webPages/safe+harbor+list</a>. For more information about the Safe Harbor Principles, please visit the U.S. Department of Commerce’s Website at <a href="http://export.gov/safeharbor/" class="auLoc-link" target="_blank">http://export.gov/safeharbor/</a>.  If You have any questions regarding this statement or our compliance program, please contact us using the contact information provided at the end of this document.</p>
						<p class="auSubHeader">Links</p>
						<p class="auTextBlock">This Website contains links to other web sites at which personal information may be collected. In such instances, unless otherwise expressly specified, the privacy policy applicable to that other web site will govern the collection and use of Your information. Kerio is not responsible for the privacy practices of such other web sites and urges You to review such web sites’ privacy practices prior to submitting any personal information.</p>
						<p class="auSubHeader">Disclosure of Your Personal Information</p>
						<p class="auTextBlock">Kerio will not sell Your personal information to anyone. We may share Your information to a local partner (distributor or reseller) in order to facilitate Your purchase and use of our Products or Services, or to agents who perform limited functions on our behalf, such as delivering packages and processing payments. We use a variety of third party providers to assist us in hosting, infrastructure, billing, sales marketing and other functions. While these providers may have access to Your personal information, they are contractually restricted from any usage thereof. These third parties are contractually restricted in their use of such information. We may also share aggregated information with our partners and advertisers; our infrastructure provider may also have access to this data.</p>
						<p class="auTextBlock">Kerio’s Products and Services include collaboration features that by their nature support sharing with users You choose. Those users can see Your name, email address, photo and information from Your Profile page, and any files You choose to share; and they can post comments and email You. Collaborators You invite as editors can also edit Your shared files, upload documents and photos to Your shared files, share those documents outside of Kerio, and give other users rights to view Your shared files.</p>
						<p class="auTextBlock">Kerio provides You with opportunities to connect with third party applications or services. If You choose to use any such third party applications or services, we may facilitate sharing of Your information including Your username and documents You choose to use with those applications and services and such third parties may contact You directly as necessary. Your use of such applications and services is not governed by Kerio’s Terms of Use or Privacy Policy. Kerio does not control the applications or services of those third parties or how they use Your information and documents. Be sure to review the terms and the privacy policies of those third parties before using their applications or services.</p>
						<p class="auTextBlock">Notwithstanding anything in this Privacy Policy to the contrary, Kerio reserves the right, unless limited by applicable law, to share any information we have collected about You or that You have submitted: (1) in order to comply with a law or legal request or to establish, protect, or exercise our legal rights or defend against legal claims; (2) if we believe it is necessary in order to investigate, prevent, or take action regarding illegal activities, fraud, or situations involving potential threats to the safety of any person or property; (3) if we believe it is necessary to investigate, prevent, or take action regarding situations that involve significant abuse of our Websites or our Products and Services (such as voluminous spamming, denial of service attacks, or attempts to compromise the security of information); (4) to our affilaited companies (in which case we will require such entities to honor this Privacy Policy);  if we are acquired by or merged with another entity; and (5) to enforce our agreements, terms of use and policies.</p>
						<p class="auSubHeader">Public Areas</p>
						<p class="auTextBlock">Your use of areas of our Websites or areas within our Products and Services that are intended for interaction with other users (e.g., product forums, message boards, and other online forums) may allow You to post personal information. By choosing to use these areas, You understand and agree that anyone may access, use, and disclose any personal information that You post to those areas.</p>
						<p class="auSubHeader">Security</p>
						<p class="auTextBlock">Kerio takes reasonable steps to protect information we collect from You to prevent loss, misuse and unauthorized access, disclosure, alteration, and destruction. In addition, highly confidential Personal Information such as a credit card number that we request from You on our Websites is protected with encryption, such as Secured Socket Layer (SSL) protocol, during transmission over the Internet.</p>
						<p class="auTextBlock">The servers on which information is stored are kept in a controlled environment with limited access. While we take reasonable efforts to guard Personal Information we knowingly collect directly from you, no security system is impenetrable. In addition, we cannot guarantee that any passively-collected personal information You choose to include in documents You store on our systems are maintained at adequate levels of protection to meet specific needs or obligations You may have relating to that information.</p>
                         
						<p class="auTextBlock">Your account information and access to our Services is accessible only through the use of an individual user ID and password. To protect the confidentiality of Personal Information, You must keep Your password confidential and not disclose it to any other person. Please advise us immediately if You believe Your password has been misused. In addition, always logout and close Your browser when You finish your session. Please note that we will never ask You to disclose your password in an unsolicited phone call or email.</p>
						<p class="auTextBlock">When You provide us with a credit card number or other financial information, Kerio will take commercially reasonable steps to protect this information through a secure connection, however, no data transmission over the Internet can be guaranteed to be 100% secure.</p>
						<p class="auSubHeader">Our Policy Toward Children</p>
						<p class="auTextBlock">Our Products and Services are not directed to persons under 13. We do not knowingly collect personally identifiable information from children under 13. If a parent or guardian becomes aware that his or her child has provided us with Personal Information without their consent, he or she should contact us at <a href="mailto:privacy@kerio.com" class="auLoc-link">privacy@kerio.com</a>. If we become aware that a child under 13 has provided us with Personal Information, we will take steps to delete such information from our files.</p>
						<p class="auSubHeader">Opt-Out</p>
						<p class="auTextBlock">Kerio may send You communications or data regarding our Websites and Products and Services, including but not limited to (i) notices about Your usage thereof, including any violations of use, (ii) updates, and (iii) promotional information and materials regarding our Products and Services. You may opt-out of receiving promotional emails from Kerio by following the opt-out instructions provided in those emails or by emailing <a href="mailto:privacy@kerio.com" class="auLoc-link">privacy@kerio.com</a>. Even if You Opt-Out, we reserve the right to send You administrative messages relating to our Website (e.g., about changes to this Privacy Policy or our Terms of Use), to contact You regarding orders You have placed (e.g., order confirmations and shipment tracking information), and with respect to such orders, to share Your information with our agents as discussed above.</p>
						<p class="auSubHeader">Enforcement</p>
						<p class="auTextBlock">If You have any questions about this Privacy Policy, please contact our General Counsel (Legal Department) at <a href="mailto:privacy@kerio.com" class="auLoc-link">privacy@kerio.com</a>. If Your inquiry has not been satisfactorily addressed, You should then contact our dispute resolution provider JAMS (<a href="http://www.jamsadr.com" class="auLoc-link" target="_blank">www.JAMSadr.com</a>). JAMS provides arbitration and mediation services.</p>
						<p class="auSubHeader">Contact Us</p>
						<p class="auTextBlock">If You need to contact a Kerio representative in the U.S. for any reason, You can reach us by phone at: 1-408-496-4500, or by fax at: 1-408-496-6902. Our postal address is: Kerio Technologies, Inc., 111 North Market Street, 6th Floor, San Jose, CA 95113, USA. Our local representatives can be found on our Website at <a href="http://www.kerio.com/company/locations" class="auLoc-link" target="_blank">www.kerio.com/company/locations</a>.</p>
						<p class="auFinePrint">This Privacy Policy was last updated January 26, 2013.</p>
					</div>
					<div id="sla-content" class="kcontent">
						<p class="auSubHeader">Samepage Service Level Agreement (SLA)</p>
						<p class="auTextBlock">As part of our agreement to provide Samepage services to You , we will meet the following service level guarantee:</p>
						<p class="auSubHeader">Service Level Guaranty</p>
						<p class="auTextBlock">We guaranty that Samepage services will be available 99.99% of the time in any given calendar month period (more specifically defined below as Monthly Uptime Percentage).</p>
						<p class="auSubHeader">Credits</p>
						<p class="auTextBlock">If we fail to meet the guaranty stated above, You will be eligible for a service credit, as stated below. Credits will be calculated as a percentage of the fees You’ve incurred during the month of Your billing cycle in which You were adversely effected (to be applied at the beginning of the next billing cycle).</p>
						<table cellpadding="0" cellspacing="0" class="auTableBlock">
							<tr><th>Montly Uptime Percentage</th><th>Service Credit</th></tr>
							<tr><td>&lt; 99.9%</td><td>10%</td></tr>
							<tr><td>&lt; 99%</td><td>25%</td></tr>
							<tr><td>&lt; 95%</td><td>50%</td></tr>
						</table>
						<p class="auTextBlock"><b>The credits awarded above are Your sole and exclusive remedy for Samepage unavailability.</b></p>
						<hr />
						<p class="auTextBlock">This SLA does not apply to any performance or availability issues:</p>
						<ol class="auTextBlock">
							<li class="auTextBlock">Caused by factors outside Kerio’s reasonable control;</li>
							<li class="auTextBlock">That resulted from Your or third party hardware or software;</li>
							<li class="auTextBlock">That resulted from actions or inactions of You or third parties, to include, but not limited to:<br />
								<ol class="auTextBlock-li-alpha">
									<li class="auTextBlock-li-alpha">Your breach of the Samepage Terms of Service (e.g., if Your account has a past due unpaid balance) and any related agreements or policies,</li>
									<li class="auTextBlock-li-alpha">Your failure to adhere to required configurations,</li>
									<li class="auTextBlock-li-alpha">Your use of non-supported platforms,</li>
									<li class="auTextBlock-li-alpha">Your misuse Your Samepage account in any way (see <a href="#" class="auLoc-link">Acceptable Use Policy</a>), or</li>
								</ol>
							</li>
							<li class="auTextBlock">During Scheduled Downtime (of which we shall attempt to provide advanced notice); or</li>
							<li class="auTextBlock">During beta, trial services or other non-paid services.</li>
						</ol>
						<p class="auSubHeader">Definitions, for purposes of this SLA:</p>
						<p class="auTextBlock">“Downtime” is defined as any period of time when users are unable to access Samepage for which they have appropriate permissions.  The ability to access Samepage is determined by automated monitoring that attempts to render Samepage every minute supplemented by server logs. Downtime for all users is calculated by the sum of all minutes Samepage is inaccessible.</p>
						<p class="auTextBlock">“Scheduled Downtime” is defined as: (i) Downtime within pre-established maintenance windows; or (ii) Downtime during hardware or software maintenance or upgrades scheduled by Kerio or requested by You.</p>
						<p class="auTextBlock">“Monthly Uptime Percentage” is calculated by taking the total number of minutes in a calendar month  minus the total number of minutes of Downtime experienced by all users in that month, all divided by the total number of minutes in that calendar month.</p>
						<p class="auFinePrint">Please note that we reserve the right to revise this SLA at any time without prior notice, although we will make reasonable efforts to provide prior notice via email.</p>
					</div>
					<div id="tos-content" class="kcontent">
						<p class="auSubHeader">Samepage Terms of Service</p>
						<p class="auTextBlock">Welcome to Samepage! These terms of service (“Terms”) form an agreement between You (“You”, Your”), and any organization You represent, and Kerio Technologies Inc. (“Kerio”, “we”, “us” or “our”). By clicking the box below and/or by any usage of our hosted document collaboration services, You agree that these Terms govern Your access to the Samepage website (the “Website”) and Your usage of our services, the software embedded in the Services (the “Software”), the downloadable software available for utilization with the Services (the “Clients”), and any associated documentation (the Website, the services and the Software and Clients are collectively referred to herein as the “Services”). If You are subscribing on behalf of any organization and You are NOT its authorized legal representative or if You do not agree with the Terms as discussed below (to include the terms provided in the associated agreements and policies referenced below), do NOT click the Kerio below and abandon the signup process. </p>
						<p class="auSubHeader">About Samepage</p>
						<p class="auTextBlock">Samepage is a cloud hosted document collaboration solution which allows You to upload, store, share and process data, files, materials text, audio, video, images and other content (“Content”) online. Samepage is offered in both a free and a paid version (aka a “Free Account” and a “Premium Account”). A description of each of the account options, to include features, capabilities and limitations included therein and pricing terms for a Premium Account are provided under the “Pricing” tab. You may also download (i) the Samepage desktop client to allow You to synchronize Your files in the cloud from Your desktop device; and (ii) and our mobile client to allow You to effectively access Your Samepage account from Your mobile device.</p>
						<p class="auSubHeader">Using our Services</p>
						<p class="auTextBlock">To begin using the Services, You are required to create a Free Starter Plan Account with Kerio (become a "Registered User"), by completing a registration form and designating a user ID and password. Until You apply for and are approved by Kerio to become a Registered User, Your access to the Services is limited. When registering with Kerio You must: (a) provide true, accurate, current and complete information about Yourself as requested by the Services’ registration form (such information being the "Registration Data") and (b) maintain and promptly update the Registration Data to keep it true, accurate, current and complete. Kerio may withdraw such approval at any time in its sole discretion, with or without cause.</p>
						<p class="auTextBlock">Only You may use Your account. You must keep Your account and password confidential. You must contact us right away if You suspect misuse of Your account or Your Content or if if You suspect any security breach in the Services. You are responsible for all activities that take place with Your account. Kerio will not be liable for any loss or damage arising from any unauthorized use of Your account.</p>
						<p class="auTextBlock">If a third party such as an employer, or school gave You Your account, that party has rights to Your account and may (i) manage Your account, reset Your password, or suspend or cancel Your account;(ii) view Your account's usage and profile data, including how and when Your account is used; and (iii) read or store Content in Your account. </p>
						<p class="auSubHeader">Levels of Service</p>
						<p class="auTextBlock">Kerio will provide guaranteed levels of service, with rights and remedies as described in the Samepage Service Level Agreement (“<a href="/cloud/terms/?sla" class="auLoc-link">SLA</a>”). The SLA is subject to change at any time without notice, although Kerio will make reasonable efforts to provide two weeks notice (but preferably thirty (30) calendar days if at all possible) to You on this Website.</p>
						<p class="auSubHeader">Acceptable Use of the Services</p>
						<p class="auTextBlock">Access to and use of the Services by You is governed under these Terms and the Samepage Acceptable Use Policy (the "<a href="/cloud/terms/?aup" class="auLoc-link">AUP</a>"). We retain the right to block or otherwise prevent delivery of any type of file, email or other communication to or from the Services as part of our efforts to protect the Services, protect You and our customers, and/or stop You from breaching these Terms. We may also suspend or terminate Your Account at any time without notice if You violate the AUP.</p>
						<p class="auSubHeader">Content</p>
						<p class="auTextBlock">You are solely responsible and liable for Your Content, which we define as any Content You upload, store, process and/or share or any Content that is shared with You. You will: (a) be solely responsible for the nature, quality and accuracy of the Content; (b) ensure that the Content (including the storage or transmission thereof) complies with these Terms and any and all applicable laws; (c) promptly handle and resolve any notices and claims relating to the Content, including any notices sent to You by any person claiming that any Content violates any person's rights, such as take-down notices pursuant to the Digital Millennium Copyright Act and any other notices; and (d) maintain appropriate security, protection and backup copies of the Content, which may include, Your use of additional encryption technology to protect the Content from unauthorized access.</p>
						<p class="auTextBlock">You own Your Content. You represent and warrant that: (a) You have all the rights in the Content contained in Your Account; and (b) the storage, use or transmission of the Content doesn't violate any law or these Terms. Except for material that we license to You, we don't claim ownership of any Content that is transmitted, stored, or processed in Your account. We also don't control, verify, or endorse the Content that You and others make available on or from Your account using the Services.</p>
						<p class="auTextBlock">We provide functions that allow You to control who may access Your Content. If You enable the features that allow You to share the Content with others, anyone You've shared content with (including the general public, in certain circumstances) may have access to Your Content.</p>
						<p class="auTextBlock">You hereby grant Kerio, its employees and agents the right, to use, modify, adapt, reproduce, distribute, display and disclose Content posted on Your Account solely to the extent necessary to provide the Services or as otherwise permitted by these Terms.<br />Kerio has no liability of any kind as a result of the deletion of, correction of, destruction of, damage to, loss of or failure to store or encrypt any Content.</p>
						<p class="auSubHeader">Content Stored Elsewhere</p>
						<p class="auTextBlock">By using and accessing the Services, You understand and consent to the storage and processing of Your Content and any other personal information outside of the country where You are located and utilizing the Services from. However, as discussed in more detail in our <a href="/cloud/terms/?privacy" class="auLoc-link">Privacy Policy</a>, Kerio does abide by the safe harbor framework set forth by the U.S. Department of Commerce regarding the collection, use, and retention of personal information.</p>
						<p class="auSubHeader">Fees and Billing; No Refunds</p>
						<p class="auTextBlock">If You upgrade from a Free to a Premium Account, You will be billed in accordance with the <a href="/cloud/terms/?billing" class="auLoc-link">Billing Terms</a>.  Failure to pay all Fees on time may result in suspension or termination of Your account.</p>
						<p class="auSubHeader">Customer Service and Technical Support</p>
						<p class="auTextBlock">Technical support will be provided in accordance with current Kerio technical support policies. Instructions for receiving support are provided under the “<a href="/help/" class="auLoc-link">Technical Support</a>” tab on the front page of the Website.</p>
						<p class="auSubHeader">Suspension and/or Termination of Your Account</p>
						<p class="auTextBlock">You may terminate Your account and/or stop using the Services at any time.</p>
						<p class="auTextBlock">Kerio reserves the right, to suspend or terminate Your Free Account at any time, with or without notice and without incurring any liability. Likely, we will terminate Your Free Account if it goes inactive for a period of thirty (30) days; we also reserve the right to terminate all of Your Content in such case.</p>
						<p class="auTextBlock">We reserve the right to suspend or terminate Your Premium Account at any time by providing written notice thereof if You breach (a) any material term or condition hereof, to include but not limited to Your violation of (i) the AUP and Your obligations under these Terms regarding usage of the Services and Content, (ii) Your obligation to pay all Fees and charges related to Your Premium Account under the Billing Terms as they become due, (iii) the provisions herein regarding Intellectual Property Rights and Notices; or (b) any non-material term or condition hereof in which You fail to cure such breach within a thirty (30) days of receiving notice thereof.</p>
						<p class="auTextBlock">In the event of a suspension by us of Your Premium Account, we will not erase any of Your Content or data stored on the Services for 30 days (the cure period) thereafter.</p>
						<p class="auTextBlock">In the event of termination of Your Premium Account, we have no obligation to continue to store Your data. However, for a period of thirty (30) days following termination, we will make reasonable efforts to assist You in data retrieval efforts, conditional upon Your payment of all outstanding payment obligations to us and possible additional storage and retrieval charges.</p>
						<p class="auSubHeader">Modification, Suspension or Termination of the Services</p>
						<p class="auTextBlock">Kerio may modify, suspend or terminate its provision of the Services or any part thereof at any time without advanced notice  and without incurring any liability by providing written notice to its customers (i) if required by law, (ii) if Kerio is required to do so based on pending third party intellectual property infringement claims, (iii) if Kerio’s relationship with any third party technology provider who provides Kerio technology, software or infrastructure is immediately discontinued.</p>
						<p class="auSubHeader">Suspension of Services Due to Maintenance or Outages</p>
						<p class="auTextBlock">Kerio reserves the right, in its sole discretion, to make necessary scheduled or unscheduled maintenance or deployments of changes, updates or enhancements to the Services at any time. We may forced to temporarily suspend the Services due to unplanned technical problems and outages. In either circumstance, we will make commercially reasonably efforts to notify You in advance if access to the Services becomes unavailable.</p>
						<p class="auSubHeader">Third Party Services and Content</p>
						<p class="auTextBlock">The Services may contain features and functionalities linking You or providing You with certain functionality and access to third party content, including websites, directories, servers, networks, systems, information and databases, applications, software, programs, products or services, and the Internet as a whole; You acknowledge that we are not responsible for such content or services. We may also provide some content to You as part of the Services. However, Kerio is not an agent of any transacting party, nor are we a direct party in any such transaction. Any such activities, and any terms associated with such activities, are solely between You and the applicable third-party. Similarly, we are not responsible for any third party content You access with the Services, and You irrevocably waive any claim against us with respect to such sites and third-party content. Kerio shall have no liability, obligation or responsibility for any such correspondence, purchase or promotion between You and any such third-party. You should make whatever investigation You feel necessary or appropriate before proceeding with any online or offline transaction with any of these third parties. You are solely responsible for Your dealings with any third party related to the Services, including the delivery of and payment for goods and services. Should You have any problems resulting from Your use of any third party services, or should You suffer data loss or other losses as a result of problems with any of Your other service providers or any third-party services, we will not be responsible unless the problem was the direct result of our breaches.</p>
						<p class="auSubHeader">Intellectual Property Rights</p>
						<p class="auTextBlock">As between You and Kerio, we or our licensors own and reserve all right, title and interest in and to the Services, the Software and all elements thereof, other than the rights explicitly granted to You to use the Services in accordance with these Terms. No title to or ownership of any proprietary rights related to the Services or the Software is transferred to You pursuant to these Terms. All rights not explicitly granted to You are reserved by us.</p>
						<p class="auTextBlock">In the event that You provide comments, suggestions and recommendations to us with respect to the Services (including, without limitation, with respect to modifications, enhancements, improvements and other changes to the Service) (collectively, "Feedback"), You hereby grant to us a world-wide, royalty free, irrevocable, perpetual license to use and otherwise incorporate any Feedback in connection with the Services. While You have a right to use the Services once You have successfully registered Your Samepage Account and subject to these Terms, You have no license to the Software itself.</p>
						<p class="auTextBlock">You may download the various Clients, desktop client or mobile application, for usage with Samepage only. We also reserve all rights to the Clients. However, You have a limited, non-exclusive, nontransferable, revocable license to use the Clients solely to access the Services during the period in which Your account is valid. You must not reverse engineer or decompile the Clients. Our Services may update the Clients automatically when a new version is available. Once Your account is terminated, You must promptly uninstall any Clients You are using.</p>
						<p class="auTextBlock">Neither during nor after Your usage of the Services will You assert against Kerio or any of its subsidiaries or affiliates (or its Third Party Technology Providers (to include but not limited to Microsoft (or its protocol licensees or its subsidiaries), zvelo or Sophos), any patent infringement or other intellectual property infringement claim with respect to the Services, or in particular the Software or technology provided therein.</p>
						<p class="auTextBlock">All software offered as part of the Services is subject to applicable U.S. export laws and <a href="http://www.bis.doc.gov/licensing/exportingbasics.htm" class="auLoc-link" target="_blank">regulations</a>, which You agree to adhere to. Additionally, You represent and warrant that You are not located in any of the following countries presently restricted by the U.S. Department of Commerce (BIS) Commerce Control List: Cuba, Iran, Iraq, Syria, Libya, North Korea and Sudan.</p>
						<p class="auSubHeader">Intellectual Property Notices</p>
						<p class="auTextBlock">The copyright notice for all contents of the Website and the Services including but not limited to design, text, software, technical drawings, configurations, graphics, other files, and their selection and arrangement is as follows: © 2005 Kerio Technologies Inc. All Rights Reserved.</p>
						<p class="auTextBlock">“Samepage” and “Kerio” are either trademarks, service marks or registered trademarks of Kerio Technologies, Inc., and may not be copied, imitated, or used, in whole or in part, without our prior written permission.</p>
						<p class="auSubHeader">Security and Data Privacy</p>
						<p class="auTextBlock">Kerio will implement reasonable and appropriate measures designed to help You secure Your Content against accidental or unlawful loss, access or disclosure. However, You are also obliged to implement reasonable and appropriate measures designed to secure such Content.</p>
						<p class="auTextBlock">In order to operate and provide the Services, we collect certain information about You. What Information we collect, how we use that Information, to whom we may disclose that Information, and how we safeguard that Information is discussed in our <a href="/cloud/terms/?privacy" class="auLoc-link">Privacy Policy</a>, which You agree to by Your use of the Services.</p>
						<p class="auSubHeader">NO WARRANTY</p>
						<p class="auTextBlock">KERIO EXPRESSLY ACKNOWLEDGES AND AGREES THAT USE OF THE SOFTWARE AND THE SERVICES, AS WELL AS USE OF THE INTERNET,  IS AT YOUR SOLE RISK AND THAT THE ENTIRE RISK AS TO THE SATISFACTORY QUALITY, PERFORMANCE AND ACCURACY, AND EFFORT IS WITH YOU. WITH THE EXCEPTION OF THE SERVICE LEVEL GUARANTEES PROVIDED IN THE SLA, WE PROVIDE THE SERVICES "AS IS", "WITH ALL FAULTS" AND "AS AVAILABLE". TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, WE MAKE NO (AND SPECIFICALLY DISCLAIM ALL) REPRESENTATIONS OR WARRANTIES OF ANY KIND, WHETHER EXPRESS, IMPLIED, STATUTORY OR OTHERWISE, INCLUDING, WITHOUT LIMITATION, ANY WARRANTY THAT THE SERVICES WILL BE UNINTERRUPTED, ERROR-FREE OR FREE OF HARMFUL COMPONENTS NOR THAT ANY DEFECTS IN EITHER THE SOFTWARE OR THE SERVICES WILL BE CORRECTED., THAT THE CONTENT WILL BE SECURE OR NOT OTHERWISE LOST OR DAMAGED, OR ANY IMPLIED WARRANTY OF MERCHANTABILITY, SATISFACTORY QUALITY, FITNESS FOR A PARTICULAR PURPOSE, OR NON-INFRINGEMENT, AND ANY WARRANTY ARISING OUT OF ANY COURSE OF PERFORMANCE, COURSE OF DEALING OR USAGE OF TRADE. SOME JURISDICTIONS DO NOT ALLOW THE FOREGOING EXCLUSIONS. IN SUCH AN EVENT SUCH EXCLUSION WILL NOT APPLY SOLELY TO THE EXTENT PROHIBITED BY APPLICABLE LAW.</p>
						<p class="auSubHeader">INDEMNIFICATION</p>
						<p class="auTextBlock">You agree to indemnify, defend and hold Kerio, its subsidiaries, affiliates, directors, officers, and employees harmless from and against any and all claims, losses, damages, liabilities, judgments, penalties, fines, costs and expenses (including reasonable attorneys fees), arising out of or in connection with any claim arising from (i) the use of the Services by You in a manner not authorized by or in violation of these Terms (to include any other agreement or policies referenced herein), and/or applicable law, (ii) any other breach by You of these Terms, (iii) Your Content, including but not limited to any claim involving infringement or misappropriation of third-party rights, violations of the right of privacy or publicity, and/or the use, development, design, manufacture, production, advertising, promotion and/or marketing of Your Content, and (iv) any act or omission by You (or Your employees and agents), to include negligence or misconduct.</p>
						<p class="auSubHeader">LIMITATION OF LIABILITY</p>
						<p class="auTextBlock">TO THE FULLEST EXTENT PERMITTED BY LAW, IN NO EVENT WILL KERIO, ITS AFFILIATES, OFFICERS, EMPLOYEES, AGENTS, DISTRIBUTORS, RESELLERS OR LICENSORS BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, PUNITIVE, COVER OR CONSEQUENTIAL DAMAGES (INCLUDING, WITHOUT LIMITATION, DAMAGES FOR LOST PROFITS, LOST DATA, BUSINESS INTERUPTION, REVENUE, GOODWILL, USE OR CONTENT) HOWEVER CAUSED, UNDER ANY THEORY OF LIABILITY, INCLUDING, WITHOUT LIMITATION, CONTRACT, TORT, WARRANTY, STRICT LIABILITY, NEGLIGENCE OR OTHERWISE, EVEN IF WE HAS BEEN ADVISED AS TO THE POSSIBILITY OF SUCH DAMAGES. TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, THE AGGREGATE LIABILITY OF KERIO AND ITS AFFILIATES, OFFICERS, EMPLOYEES, AGENTS, DISTRIBUTORS, RESELLERS OR LICENSORS, RELATING TO THE SERVICES WILL BE LIMITED TO THE GREATER OF AN AMOUNT EQUAL THREE MONTHS OF YOUR SERVICES SUBSCRIPTION FEES. THE LIMITATIONS AND EXCLUSIONS ALSO APPLY IF THIS REMEDY DOES NOT FULLY COMPENSATE YOU FOR ANY LOSSES OR FAILS OF ITS ESSENTIAL PURPOSE. SOME JURISDICTIONS DO NOT ALLOW THE LIMITATION OF INCIDENTAL, CONSEQUENTIAL OR OTHER DAMAGES. IN SUCH AN EVENT THIS LIMITATION WILL NOT APPLY TO YOU TO THE EXTENT PROHIBITED BY LAW. WE SHALL ALSO NOT BE HELD LIABLE FOR ANY DELAYS, DELIVERY FAILURES, OR OTHER DAMAGES OR OTHER PROBLEMS RESULTING FROM USE OF THE INTERNET.</p>
						<p class="auSubHeader">Copyright Complaints and Removal Policy</p>
						<p class="auTextBlock">Kerio does not tolerate content that appears to infringe any copyright or other intellectual property rights or otherwise violates these Terms and will respond to notices of alleged copyright infringement that comply with the law and are properly provided to us (see the <a href="/cloud/terms/?dmca" class="auLoc-link">DMCA</a> tab of this Website). We reserve the right to delete or disable Content alleged to violate these Terms and to terminate repeat infringers.</p>
						<p class="auSubHeader">Governing Law and Dispute Resolution</p>
						<p class="auTextBlock">Any dispute, controversy or claim arising out of or relating to these Terms or to a breach hereof, including its interpretation, performance or termination, shall be finally resolved by arbitration. The arbitration shall be conducted in English and in accordance with the arbitration rules and procedures of the JAMS (<a href="http://www.JAMSadr.com" class="auLoc-link" target="_blank">www.JAMSadr.com</a>), which shall administer such arbitration. The arbitration, including the rendering of the award, shall take place in Santa Clara County, California, USA. For the purposes of this arbitration, these Terms shall be governed by and construed under California law as such law applies to agreements between California residents entered into and to be performed within California, USA. The decision of the arbitrators shall be binding upon the parties hereto, and the expense of the arbitration (including without limitation the award of attorneys' fees to the prevailing party) shall be paid as the arbitrators determine. The decision of the arbitrators shall be executory, and judgment thereon may be entered by any court of competent jurisdiction. Notwithstanding anything contained in this Section, each party shall have the right to institute judicial proceedings against the other party or anyone acting by, through or under such other party in order to enforce the instituting party's rights hereunder through reformation of contract, specific performance, injunction or similar equitable relief.</p>
						<p class="auSubHeader">Assignment</p>
						<p class="auTextBlock">You may not assign Your rights or delegate Your duties under these Terms either in whole or in part without Kerio’s prior written consent of the other party, except to an affiliate or a party that acquires substantially all of the assigning Your assets or business or a majority of Your stock as part of a corporate merger or acquisition. Any attempted assignment or delegation without such consent will be void. This Agreement will bind and inure to the benefit of Your successors and permitted assigns.</p>
						<p class="auSubHeader">Force Majeure</p>
						<p class="auTextBlock">Except for performance of a payment obligation, neither party shall be liable under these Terms for delays, failures to perform, damages, losses or destruction, or malfunction of any equipment, or any consequence thereof, caused or occasioned by, or due to fire, earthquake, flood, water, the elements, labor disputes or shortages, utility curtailments, power failures, explosions, civil disturbances, governmental actions, shortages of equipment or supplies, unavailability of transportation, acts or omissions of third parties, or any other cause beyond its reasonable control. If the force majeure continues for more than thirty (30) calendar days, then either party may terminate Your Account for convenience upon written notice to the other party.</p>
						<p class="auSubHeader">Severability</p>
						<p class="auTextBlock">If any provision of these Terms, or a portion thereof, shall be adjudged by the arbitrator or a court of competent jurisdiction to be unenforceable or invalid, that portion shall be eliminated or limited to the minimum extent necessary so that these Terms shall remain in full force and effect and enforceable.</p>
						<p class="auSubHeader">Survival</p>
						<p class="auTextBlock">The following sections will survive the expiration, termination or rescission of these Terms: Fees, Termination of Your Account, Intellectual Property Rights, Data Privacy, Limitation of Liability, and Governing Law and Dispute Resolution.</p>
						<p class="auSubHeader">Changes to these Terms</p>
						<p class="auTextBlock">Kerio reserves the right to modify or replace these Terms at any time in our sole discretion. We will indicate at the bottom of these Terms the date these Terms were last updated. Any changes will be effective upon posting the revised version of these Terms. As such, we encourage You to check the date of these Terms whenever You visit this Website to see if these Terms have been updated. Your continued use of any portion of the Services constitutes Your acceptance of such changes. If You do not agree to any of the changes, You must cancel Your Account and stop using the Services.</p>
						<p class="auSubHeader">Entire Agreement</p>
						<p class="auTextBlock">These Terms, the Billing Terms, the AUP, the SLA, the Privacy Policy and the DMCA Policy, any other agreements and policies referenced herein (which are incorporated into these Terms by reference) and any subsequent written amendments thereto (which could include email communications between the parties) represent the sole, exclusive and integrated mutual understanding of the parties concerning Your use of the Services, and supersedes and cancels all previous and contemporaneous written and oral agreements and communications between the parties relating to the subject matter of these Terms.</p> 
						<p class="auSubHeader">Questions/Comments</p>
						<p class="auTextBlock">If You have any legal questions or comments regarding these Terms, please contact us at <a href="mailto:legal@kerio.com" class="auLoc-link">legal@kerio.com</a>.</p>
						<p class="auFinePrint">Last Updated: January 30, 2013</p>
					</div>
					<div id="aup-content" class="kcontent">
						<p class="auSubHeader">Samepage Acceptable Use Policy</p>
						<p class="auTextBlock">This Samepage Acceptable Use Policy ("AUP") describes unacceptable practices and prohibited actions while using Samepage hosted document collaboration services (these “Services” are further defined in the <a href="/cloud/terms/?tos" class="auLoc-link">Samepage Terms of Service</a>). By registering an account and using the Services, You agree to abide by this AUP, which may be amended from time to time without notice. If at any time You disagree with this AUP, You must stop using the Services. If You violate this AUP, Kerio may suspend or terminate Your Samepage Account immediately and without notice, although in some cases You may be given an opportunity to cure Your violation.</p>
						<p class="auSubHeader">Compliance and Liability</p>
						<p class="auTextBlock">This AUP is intended to protect You, us, our other customers, and the Services and Internet community in general from improper, inappropriate, abusive, or illegal activity. When using the Services, You are required to comply with this AUP and are expected to adhere to commonly accepted practices of the Internet community. The prohibited uses described below are intended as guidelines regarding improper and inappropriate conduct, and should not be interpreted as an exhaustive list.</p>
						<p class="auTextBlock">Kerio assumes no liability for Your Content (as defined in Samepage Terms of Service) or Your use of the Services.</p>
						<p class="auSubHeader">Prohibited Uses:</p>
						<p class="auSubHeader">Illegal Use</p>
						<p class="auTextBlock">The Services may only be used for lawful purposes. You may not use, or encourage, promote, facilitate or instruct others to use, the Services for any illegal, harmful or offensive use, or to transmit, store, display, distribute or otherwise make available Content that is illegal, harmful, or offensive. Prohibited activities or content include:</p>
						<ul class="auTextBlock-li-disc">
							<li class="auTextBlock-li-disc"><b>Illegal Activities</b>. Any illegal activities, including but not limited activities which constitutes an illegal threat made against any person or organization, activities which violate export control laws or regulations, activities related to advertising, transmitting, or otherwise making available gambling sites or services or disseminating, activities related to promoting or facilitating child pornography.</li>
							<li class="auTextBlock-li-disc"><b>Harmful or Fraudulent Activities</b>. Activities that may be harmful to Kerio or others, to include but not limited to offering or disseminating fraudulent goods, services, schemes, or promotions (e.g., make-money-fast schemes, ponzi and pyramid schemes, phishing, or pharming), or engaging in other deceptive practices.</li>
							<li class="auTextBlock-li-disc"><b>Infringing Content</b>. Content that infringes or misappropriates the intellectual property or proprietary rights of others.</li>
							<li class="auTextBlock-li-disc"><b>Offensive Content</b>. Content that is defamatory, obscene, indecent, abusive, invasive of privacy, or otherwise objectionable, to include but not limited to child pornography, relates to bestiality, or depicts non-consensual sex acts.</li>
							<li class="auTextBlock-li-disc"><b>Harmful Content</b>. Content or other computer technology that may damage, interfere with, surreptitiously intercept, or expropriate any system, program, or data, to include but not limited to viruses, Trojan horses, worms, time bombs, or cancelbots.</li>
						</ul>
						<p class="auSubHeader">Forgery</p>
						<p class="auTextBlock">The Services may not be used in a manner which purposely alters or forges Your identity. You may not engage, without limitation, in the following activities:</p>
						<ul class="auTextBlock-li-disc">
							<li class="auTextBlock-li-disc">Sending any message or transmitting any electronic communication using a name or address other than Your own for purposes of deception.</li>
							<li class="auTextBlock-li-disc">Impersonating someone else by altering Your source IP address or by using forged headers or other identity information.</li>
							<li class="auTextBlock-li-disc">Fraudulently concealing, forging or otherwise falsifying Your identity in connection with any use of the Services.</li>
						</ul>
						<p class="auSubHeader">Security</p>
						<p class="auTextBlock">The Services may not be used to violate the security or integrity of any application, software, computer, system, network; such behavior may result in criminal or civil liability. You may not engage, without limitation, in the following activities:</p>
						<ul class="auTextBlock-li-disc">
							<li class="auTextBlock-li-disc">Gaining unauthorized access to, or attempting to compromise or test the normal functioning, operation or security of any network, system, computing facility, equipment, data or information.</li>
							<li class="auTextBlock-li-disc">Engaging in any activities that may interfere with the ability of others to access or use the Services, their system, or the Internet (i.e., denial attacks).</li>
							<li class="auTextBlock-li-disc">Monitoring or crawling any data, information or communications on any network or system not owned by You without authorization.</li>
							<li class="auTextBlock-li-disc">Gaining unauthorized access to the user accounts or passwords of other users of any system.</li>
							<li class="auTextBlock-li-disc">Attempting to intercept, redirect or otherwise interfere with communications intended for others.</li>
							<li class="auTextBlock-li-disc">Intentionally transmitting files or messages containing computer viruses or propagating worms, Trojan horses, or "spyware" programs.</li>
							<li class="auTextBlock-li-disc">Using manual or electronic means to avoid the use limitations related to the Services, such as access and storage restrictions.</li>
							<li class="auTextBlock-li-disc">Operating network services like open proxies, open mail relays, or open recursive domain name servers.</li>
						</ul>
						<p class="auSubHeader">E-Mail</p>
						<p class="auTextBlock">The Services may not be used to distribute electronic mail in an improper or illegal manner. You may not engage, without limitation, in the following activities:</p>
						<ul class="auTextBlock-li-disc">
							<li class="auTextBlock-li-disc">Distributing, publishing, sending, or facilitating the sending of unsolicited mass e-mail (i.e., spamming) for any purpose.</li>
							<li class="auTextBlock-li-disc">Altering or obscuring packet or mail headers message origin or sender’s identity.</li>
							<li class="auTextBlock-li-disc">Enlisting a third party to transmit unsolicited mass or commercial email on Your behalf.</li>
							<li class="auTextBlock-li-disc">Collecting responses from unsolicited mass or commercial email, or advertising Your website or Your identity in such email.</li>
							<li class="auTextBlock-li-disc">Transmitting a large amount of email to a recipient with the intent to disable their system (i.e., mail bombing).</li>
							<li class="auTextBlock-li-disc">Using another party's electronic mail server to relay email without express permission.</li>
						</ul>
						<p class="auSubHeader">Usenet and Newsgroups</p>
						<p class="auTextBlock">The Services may not be used to violate the guidelines or restrictions imposed by the charter of any newsgroup. You may not engage, without limitation, in the following activities:</p>
						<ul class="auTextBlock-li-disc">
							<li class="auTextBlock-li-disc">Posting any commercial message or advertisement, unless permitted by the charter of the newsgroup.</li>
							<li class="auTextBlock-li-disc">Cross-posting a message to unrelated newsgroups or to any newsgroups where the post does not meet that newsgroup's charter.</li>
							<li class="auTextBlock-li-disc">Repetitious posting of off-topic or disruptive messages, unless specifically invited by the charter of the newsgroup.</li>
						</ul>
						<p class="auSubHeader">Monitoring and Enforcement</p>
						<p class="auTextBlock">Kerio reserves the right to investigate any violation of this AUP or misuse of the Services without notice to You. Accordingly, we may:</p>
						<ul class="auTextBlock">
							<li class="auTextBlock">investigate violations of this Policy or misuse of the Services;</li>
							<li class="auTextBlock">remove, disable access to, or modify any content or resource that violates this AUP or any other agreement we have with You for use of the Services; and/or</li>
							<li class="auTextBlock">suspend or terminate the Services.</li>
						</ul>
						<p class="auTextBlock">Kerio may report any activity that it suspects violates any law or regulation to appropriate law enforcement officials, regulators, or other appropriate third parties. Our reporting may include disclosing Your information. We also may cooperate with appropriate law enforcement agencies, regulators, or other appropriate third parties to help with the investigation and prosecution of illegal conduct by providing network and systems information related to alleged violations of this AUP. You are obligated to cooperate with us regarding the investigation and reporting of any such activity as needed. We bear no liability with regard to this provision.</p>
						<p class="auTextBlock">With respect to illegal or unlawful acts or conduct by You, we will take the above enforcement actions where it deems local law has been violated.</p>
						<p class="auSubHeader">Notification of Violation</p>
						<p class="auTextBlock">If You become aware of any violation of this AUP by any person, including downstream end-users, or third parties, You must immediately notify us via e-mail at <a href="mailto:abuse@kerio.com" class="auLoc-link">abuse@kerio.com</a>.</p>
					</div>
                    <div style="display:none">
						<div id="greenbar"></div>
					</div>
					
				</div>
			</div>
		</div>
	</div><div class="roomsub"></div>
</div>
</div>

